# Problem Set 1

## Problem 1: For Loop.

#### A: To print the numbers 0 to 100.

In [1]:
for i in range(101):
    print(i, end = " ")

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99 100 

#### B: To print the numbers 0 to 100 that are divisible by 7.

In [2]:
for i in range(0, 101):
    if i%7 == 0:
        print(i, end = " ")

0 7 14 21 28 35 42 49 56 63 70 77 84 91 98 

#### C: Print the numbers 1 to 100 that are divisible by 5, but not 3.

In [3]:
for i in range(0, 100):
    if i%5 == 0:
        if i%3 != 0:
            print(i, end = " ")

5 10 20 25 35 40 50 55 65 70 80 85 95 

#### D: Print for each of the numbers x = 2, ..., 20 all the numbers that divide x, excluding 1 and x. Hence, for 18, it should print: 2 3 6 9.

In [4]:
print("Printing the numbers from 2 to 20, and their divisors (excluding 1, and itself):")

for i in range(2,21):
    print("\n" + str(i))
    print("Divisor(s): ")
    for j in range(1, i+1):
        if i%j == 0 and j != 1 and j != i:
            print(str(j), end = " ")
    print()

Printing the numbers from 2 to 20, and their divisors (excluding 1, and itself):

2
Divisor(s): 


3
Divisor(s): 


4
Divisor(s): 
2 

5
Divisor(s): 


6
Divisor(s): 
2 3 

7
Divisor(s): 


8
Divisor(s): 
2 4 

9
Divisor(s): 
3 

10
Divisor(s): 
2 5 

11
Divisor(s): 


12
Divisor(s): 
2 3 4 6 

13
Divisor(s): 


14
Divisor(s): 
2 7 

15
Divisor(s): 
3 5 

16
Divisor(s): 
2 4 8 

17
Divisor(s): 


18
Divisor(s): 
2 3 6 9 

19
Divisor(s): 


20
Divisor(s): 
2 4 5 10 


#### E: The smallest number that is divisible by 2, 3, and 4 is 12. Find the smallest number that is divisible by all the integers between 1 and 10.

In [5]:
i = 1

while True:
    if i%1 == 0 and i%2 == 0 and i%3 == 0 and i%4 == 0 and i%5 == 0 and i%6 == 0 and i%7 == 0 and i%8 == 0 and i%9 == 0 and i%10 == 0:
        print("The smallest number that is divisible by the first 10 integers is: " + str(i))
        break
    else:
        i += 1

The smallest number that is divisible by the first 10 integers is: 2520


## Problem 2: Numpy

In [6]:
#Generate: a 200 x 500 matrix A with random Gaussian entries, a 500 x 500 matrix B with Toeplitz entries.
import numpy as np
from scipy.linalg import toeplitz

#Creating a 200x500 Gaussian matrix.
A = np.random.normal(0, 1, (200, 500))

#Creating a 500x500 Toeplitz matrix.
sequence = np.arange(1, 501, 1)
B = toeplitz(sequence, sequence)

#### A1. Calculate $A$ $+$ $A$

In [7]:
A + A

array([[ 3.79823497,  0.58960818,  3.07977511, ..., -0.86120799,
         0.1245517 ,  2.91595651],
       [-2.28137926, -0.04580035,  0.14341908, ..., -2.93986347,
        -3.7753106 , -0.2349667 ],
       [-1.09825569, -0.41301178,  0.21689455, ...,  1.60590638,
         0.58720967, -3.55912094],
       ...,
       [ 1.6895745 ,  2.92387284, -3.86113389, ...,  2.23998433,
         1.49524734, -0.0477425 ],
       [ 0.22698853,  0.48453927, -0.45114503, ..., -0.92614942,
        -0.85850518, -1.07525714],
       [ 0.54548495,  0.02061169,  2.59140516, ..., -1.49188264,
         0.56533391,  0.0386275 ]])

#### A3. Calculate $A$$A^{T}$

In [8]:
A.dot(A.T)

array([[ 4.94302503e+02, -1.22597094e+00,  1.44804526e+01, ...,
        -6.94596246e-02, -2.49347061e+01,  1.38355664e+01],
       [-1.22597094e+00,  5.04896195e+02, -2.74965943e+01, ...,
        -3.14222202e+01, -3.55753385e+01, -4.75272359e+01],
       [ 1.44804526e+01, -2.74965943e+01,  4.83084209e+02, ...,
        -1.48110251e+01, -1.46439239e+01, -1.03455323e+01],
       ...,
       [-6.94596246e-02, -3.14222202e+01, -1.48110251e+01, ...,
         4.97202063e+02, -2.65221464e+01, -1.52582374e+01],
       [-2.49347061e+01, -3.55753385e+01, -1.46439239e+01, ...,
        -2.65221464e+01,  4.55205636e+02,  1.46395198e+01],
       [ 1.38355664e+01, -4.75272359e+01, -1.03455323e+01, ...,
        -1.52582374e+01,  1.46395198e+01,  5.13199682e+02]])

#### A3. Calculate $A^{T}$$A$

In [9]:
A.T.dot(A)

array([[193.0323962 ,   5.02369846,   4.08670036, ...,   5.03364956,
         -7.79344989,  17.60920659],
       [  5.02369846, 223.06797938,  30.55479976, ...,  -3.49566726,
         15.57924445,  11.57403435],
       [  4.08670036,  30.55479976, 181.7878885 , ...,   3.15407305,
         -0.66270925, -10.48029472],
       ...,
       [  5.03364956,  -3.49566726,   3.15407305, ..., 214.29546639,
          0.75419817,   3.36026282],
       [ -7.79344989,  15.57924445,  -0.66270925, ...,   0.75419817,
        208.14309527,  -5.58438051],
       [ 17.60920659,  11.57403435, -10.48029472, ...,   3.36026282,
         -5.58438051, 191.31675281]])

#### A4. Calculate $A$$B$

In [10]:
A.dot(B)

array([[ -937.74454345,  -931.53893944,  -924.74372725, ...,
         -257.57614553,  -263.02402279,  -268.34734835],
       [  923.14687912,   927.5590412 ,   931.92540293, ...,
        -4267.46925167, -4270.15251571, -4276.61109034],
       [-4480.05626856, -4453.6140789 , -4427.58490103, ...,
        -9269.15699054, -9293.72552461, -9317.70684901],
       ...,
       [-1180.41338315, -1178.82950354, -1174.32175109, ...,
         1234.55489481,  1233.21308486,  1233.36652225],
       [15605.83391821, 15554.91088644, 15504.47239392, ...,
         9915.01719755,  9968.10098018, 10020.32625764],
       [-5623.85024084, -5609.90609845, -5595.94134436, ...,
        -1061.43723588, -1075.43985474, -1088.87713968]])

#### B. Solving a linear system. Generate a vector b with 500 enties and solve $B$$x$ $=$ $b$

In [11]:
#Generating an array of 500 entries with values ranging from 0-500.
b = np.random.randint(501, size = 500)
#Solving for x.
x = np.linalg.solve(B, b)

#Checking the solution.
np.allclose(np.dot(B, x), b)

True

#### C. Nearest neighbor. Write a for loop that takes a value $z$ and an array $A$ and finds the element in $A$ that is closest to $z$.It should print the closest value, not the index. Hint: use the built-in functionality of Numpy rather than writing code to find this value manually. In particular, use brackets and argmin.

In [25]:
#Generating an array of 10 entries from 1-10.
A = np.arange(1, 11, 1)
print("The array A is: " + str(A))
while True:
    #Checking for a float.
    try: 
        #Asking the user for a float.
        z = float(input("Enter a number: "))
        if type(z) is float:
            print("You entered: " + str(z))
            #Calculating an array of the distance between the values in A and the float z.
            B = abs(A - z)
            #Printing the position of the number closest to z.
            print("The position of the closest value in A to your number is: " + str(np.argmin(B)))
            #Printing the number closest to z.
            print("The closest value in A to your number is: " + str(A[np.argmin(B)]))
            break
    except:
        print("That wasn't a number. Try again. ")

The array A is: [ 1  2  3  4  5  6  7  8  9 10]


Enter a number:  2.1


You entered: 2.1
The position of the closest value in A to your number is: 1
The closest value in A to your number is: 2


## Problem 3: Pandas

#### Complete the exercises that we started during the class.

In [35]:
#Generating an array of 10 entries from 1-10.
A = np.arange(1, 11, 1)
print("The array A is: " + str(A))

#Utilizing a while loop to repeatedly ask the user for a number until provided.
while True:
    try: 
        #Asking the user for a float.
        z = float(input("Enter a number: "))
        if type(z) is float:
            print("You entered: " + str(z))
            #Calculating an array of the distance between the values in A and the float z.
            B = abs(A - z)
            #Printing the position of the number closest to z.
            print("The position of the closest value in A to your number is: " + str(np.argmin(B)))
            #Printing the number closest to z.
            print("The closest value in A to your number is: " + str(A[np.argmin(B)]))
            break
    except:
        print("That wasn't a number. Try again. ")

The array A is: [ 1  2  3  4  5  6  7  8  9 10]


Enter a number:  4


You entered: 4.0
The position of the closest value in A to your number is: 3
The closest value in A to your number is: 4


In [32]:
#Trying to implement a for loop into the code for no particular reason.


#Generating an array of 10 entries from 1-10.
A = np.arange(1, 11, 1)
print("The array A is: " + str(A))

k = A[0]

try: 
    #Asking the user for a float.
    z = float(input("Enter a number: "))
    if type(z) is float:
        print("You entered: " + str(z))
        #Calculating an array of the distance between the values in A and the float z.
        for i in A:
            j = abs(A[i] - z)
            if k <= j:
                k = j
        #Printing the position of the number closest to z.
        print("The position of the closest value in A to your number is: " + str(np.argmin(B)))
        #Printing the number closest to z.
        print("The closest value in A to your number is: " + str(A[np.argmin(B)]))
        print(str(k))
except:
    print("That wasn't a number. Try again. ")

The array A is: [ 1  2  3  4  5  6  7  8  9 10]


Enter a number:  3.4


You entered: 3.4
That wasn't a number. Try again. 
